name: Actions Workflows

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-20.04
    steps:
      - name: simple js Actions
        id: greet
        
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: aris
      - name: get greeting time
        run: /home/runner/work/_temp/1cf4d84e-15be-4e77-895e-5996f8e534ef.sh
        #run: "${{ steps.greet.outputs.time }}"
